# 线性代数基础
线性代数是数学中处理具有多维结构的数字序列的一个分支。这些多维结构被称为标量、向量、矩阵和张量。人工智能需要处理非常多的数值，而使用线性代数可以利用简单的公式来表达对多个数值的处理。而且，可以利用numpy轻松地将公式应用于代码中。

虽然真正学习线性代数需要花费大量的精力和时间，但本章内容仅限于初学人工智能所需的范围。

学会灵活运用线性代数，可以高校地处理大量的数值数据。


本章是数学教科书的第四章节，主要学习线性代数的相关基础知识，主要涉及的内容有
- 标量、向量、矩阵、张量
- 向量点积
  - 向量叉积 cross product
- 向量范数
- 矩阵的积
  - 哈达玛积
- 矩阵转置
- 行列式与逆矩阵
- 线性变化
- 特征值和特征向量
- 余弦相似度


## 1）标量、向量、矩阵和张量

编程语言中往往有基础数据类型和组合数据类型，基础数据类型如字符、整形、浮点数，是原子个体的类型；但孤立的数据在处理时缺乏效率并且缺乏相应的表示能力；组合数据类型如数组、字符串、对象等则将基础数据类型根据规则进行了组织，增加了数据表达能力，便利了程序处理提高了效率。人工智能的训练同样需要对大量的数据进行处理，因此需要在数据层面对数据进行编码，表示，计算等，而标量、向量、矩阵和张量正是这个过程中所需的重要工具，他们在不同的数据维度上发挥作用。

### a-标量 scaler

标量（scaler）就是像1、5、1.2、-7 等正常的数字。一般用小写英语或希腊字母表示

标量的示例：$a、p、\alpha、\gamma $

python中处理的正常数值就与标量对应  


In [1]:
# python 中的标量
a = 1
b = 1.2
c = -0.25
d = 1.2e5

[a,b,c,d]

[1, 1.2, -0.25, 120000.0]

### b-向量 vector

标量只表示数值大小，而向量通过标量的组合不仅表示大小而且表示方向，标量的个数反映了向量的维度。

向量的写法是将标量排列在直线上，通常用一个小写字母加上箭头表示

向量包括垂直排列数值的垂直向量，以及水平排列数值的水平向量。本书主要使用水平向量，因此单纯写作向量时所指的是水平向量

在python中可以使用 Numpy 的一维数组来表示向量

In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


### c-矩阵 matrix

矩阵是将标量排列成格子状的产物，在矩阵中，标量的水平排列被称为行，标量的垂直排列被称为列。m行n列矩阵表示为 $m\times n$ 矩阵

因此，下图的矩阵就是 $3\times3$ 矩阵。

矩阵一般用大写的斜体字母表示

$$
 \begin{bmatrix}
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9
  \end{bmatrix}
  \tag{2}
$$

Numpy的二维数组可以表示矩阵

In [3]:

a = np.array([[1,2,3],
              [4,5,6]])

print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])

print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


### d-张量 tensor

张量是在多个维度中排列的标量，其中包括标量、向量和矩阵。

每个元素的下标数被称为张量的**阶数**。标量没有下标，因此它是0阶向量，向量有1个下标，因此为1阶张量，矩阵有2个下标，因此为2阶张量。

更高维度的还有3阶张量、4阶张量

> 这里对于张量的定义采取了简化的定义，在数学和物理中，张量的定义实际上要更为复杂

可以使用Numpy的多维数组来表示3阶张量

In [ ]:

a = np.array([[
                [0,1,2,3],
                [2,3,4,5],
                [4,5,6,7]
              ],
              [
                [1,2,3,4],
                [3,4,5,6],
                [5,6,7,8]
              ]])



# 自主拓展

### 1-向量叉积
向量积（也称为叉积）定义为
$$\textbf{e} = \textbf{a} \times \textbf{b} = \lvert a \rvert\ \lvert b \rvert\ \sin(\theta)\hat{n}$$
---
$$
\left( \begin{array}{c}
e_x \\
e_y \\
e_z \end{array} \right) =
\left(
\begin{array}{c}
a_x \\
a_y \\
a_z
\end{array} \right)
\times
\left(
\begin{array}{c}
b_x \\
b_y \\
b_z
\end{array}
\right)
=
\left(
\begin{array}{c}
a_yb_z - a_zb_y \\
a_zb_x - a_xb_z\\
a_xb_y - a_yb_x

\end{array}
\right)$$
从几何角度来说，叉积的长度等于 $a$ 和 $b$ 的大小乘以它们之间的角度的正弦值。它指向 $\hat{n}$ 的方向，这是直接指向 $a$ 和 $b$ 所在平面的向量。这意味着如果两个向量指向方向相同（或完全相反），那么它们的叉积将为零。试试上面的方法吧！

# 学习工具

### 数学可视化
https://academo.org/demos/3d-vector-plotter/