In [1]:
import numpy as np


In [41]:
# 1) 创建numpy数组

# 1.1 array 方法转换类型

# 1.1.1 一维数组
na = np.array([1, 2, 3])
print(na, na.shape)
# 1.1.2 二维数组
na = np.array([[1, 2, 3], [4, 1, 3]], order='F')
print(na, na.shape)
# 1.1.3 三维数组
na = np.array([[[1, 2, 3], [1, 2, 3]]])
# ! order参数决定了数组在内存中的排放方式，也因此导致读取时的不同方式，因此会影响resize等原地改变数组方法的结果
print(na, na.shape)
# 1.1.4 C：row方向
na = np.array([[1, 2, 3], [4, 1, 3]], order='C')
print("order='C'\n",  na, na.shape)
print(na[0])
# 1.1.4 F：column方向
na = np.array([[1, 2, 3], [4, 1, 3]], order='F')
print("order='F'\n",  na, na.shape)
print(na[0])

# 1.2 批量数组
# 1.2.1 零数组
na = np.zeros([1,2], np.float32)
print(na, na.shape)
# 1.2.2 一数组
na = np.ones([2, 2], np.complex64)
print(na, na.shape)
# 1.2.3 range顺序数组
na = np.arange(1, 10, 2, dtype=np.complex128)
print(na, na.shape)
# 1.2.4 填充数组



[1 2 3] (3,)
[[1 2 3]
 [4 1 3]] (2, 3)
[[[1 2 3]
  [1 2 3]]] (1, 2, 3)
order='C'
 [[1 2 3]
 [4 1 3]] (2, 3)
[1 2 3]
order='F'
 [[1 2 3]
 [4 1 3]] (2, 3)
[1 2 3]
[[0. 0.]] (1, 2)
[[1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]] (2, 2)
[1.+0.j 3.+0.j 5.+0.j 7.+0.j 9.+0.j] (5,)


In [47]:
# 2) ndarray数组形状

# 2.1 shape 查看形态
na = np.ones([2,4])
print(na)
print("shape:", na.shape)
print("size", na.size)

# 2.2 reshape 重构形态
na = na.reshape([8])
print(na)
print("shape:", na.shape)
print("size", na.size)

# 2.3 resize 重构大小
na.resize([2,4])
print(na)
print("shape:", na.shape)
print("size", na.size)

# 2.3.1 C方向
na = np.array([[1, 2, 3], [1, 2, 3]], order='C')
print(na)
na.resize([2,1])
print(na)
# 2.3.2 F方向
na = np.array([[1, 2, 3], [1, 2, 3]], order='F')
print(na)
na.resize([2, 1])
print(na)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (2, 4)
size 8
[1. 1. 1. 1. 1. 1. 1. 1.]
shape: (8,)
size 8
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (2, 4)
size 8
[[1 2 3]
 [1 2 3]]
[[1]
 [2]]
[[1 2 3]
 [1 2 3]]
[[1]
 [1]]
